FROM docker.io/library/debian:latest

RUN apt-get update && apt-get install -y python3 python3-pip python3-plotly python3-pymysql python3-netaddr python3-pyroute2 python3-flask && apt-get clean all
COPY graphtext.py /root/code/graphtext.py
COPY db.py /root/code/db.py
COPY socketfinder.py /root/code/socketfinder.py

WORKDIR /root/code
ENTRYPOINT ["python3", "/root/code/graphtext.py"]

LABEL RUN="podman run -dt -p 5000:5000 IMAGE"
