FROM docker.io/library/debian:latest

RUN apt-get update && apt-get install -y python3 python3-pymysql python3-netaddr python3-pyroute2 && apt-get clean all
COPY db.py /root/code/db.py
COPY socketfinder.py /root/code/socketfinder.py
COPY generatenums.py /root/code/generatenums.py
WORKDIR /root/code

LABEL RUN="podman run -dt --name demogen IMAGE python3 generatenums.py"
